// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hduwmtndpschshganzae.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhkdXdtdG5kcHNjaHNoZ2FuemFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwMDc3NjUsImV4cCI6MjA3MjU4Mzc2NX0.NHXZHpmyb-KoB8mQjVHckeNtcakeZ_xg0i5UhDz444Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});